add wave -group "Testbench" -radix binary   sim:/testbench/r_clk
add wave -group "Testbench" -radix binary   sim:/testbench/r_d
add wave -group "Testbench" -radix binary   sim:/testbench/w_q0
add wave -group "Testbench" -radix binary   sim:/testbench/w_q1
add wave -group "dff_0"     -radix binary   sim:/dff_0/i_clk
add wave -group "dff_0"     -radix binary   sim:/dff_0/i_d
add wave -group "dff_0"     -radix binary   sim:/dff_0/o_q
add wave -group "dff_1"     -radix binary   sim:/dff_1/i_clk
add wave -group "dff_1"     -radix binary   sim:/dff_1/i_d
add wave -group "dff_1"     -radix binary   sim:/dff_1/o_q